### ISSUE TITLE
Unable to build component library after 0.4.0

### ISSUE THREAD

**Issue by imMadsen** [qwikifiers/qwik-ui#799]
After upgrading my Component Library to 0.4.0, and implementing the interface changes. Not sure if this could be some of the issue, but I am using Bun both for package managing, and runtime.

```
Could not resolve "../../node_modules/.pnpm/@oddbird_popover-polyfill@0.4.3/node_modules/@oddbird/popover-polyfill/dist/popover.qwik.mjs" from "node_modules/@qwik-ui/headless/components/popover/use-popover.qwik.mjs"
file: C:/Users/tilra/OneDrive/Desktop/fitting-monorepo/packages/ui/node_modules/@qwik-ui/headless/components/popover/use-popover.qwik.mjs
    at getRollupError (file:///C:/Users/tilra/OneDrive/Desktop/fitting-monorepo/node_modules/rollup/dist/es/shared/parseAst.js:396:41)
    at error (file:///C:/Users/tilra/OneDrive/Desktop/fitting-monorepo/node_modules/rollup/dist/es/shared/parseAst.js:392:42)
    at ModuleLoader.handleInvalidResolvedId (file:///C:/Users/tilra/OneDrive/Desktop/fitting-monorepo/node_modules/rollup/dist/es/shared/node-entry.js:19102:24)
    at ModuleLoader.resolveDynamicImport (file:///C:/Users/tilra/OneDrive/Desktop/fitting-monorepo/node_modules/rollup/dist/es/shared/node-entry.js:19162:58)
    at async file:///C:/Users/tilra/OneDrive/Desktop/fitting-monorepo/node_modules/rollup/dist/es/shared/node-entry.js:19049:32
```

**Comment by imMadsen** [comment]
Seems like it was an issue on my end :|
